

export const message = {
    idNotFoundMessage: "Please provide user id'",
    userNotFoundMessage: "User not found",
    userAlreadyVerifiedMessage: "User already verified",
    otpAttemptsExceededMessage: "Too many attempts. Please try again later",
    otpNotFoundMessage: "Please provide otp",
    invalidOtpMessage: "Invalid otp",
    otpExpiredMessage: "OTP expired. Generate new otp",
    loginSuccessfulMessage: "Login successful",
    userVerifiedMessage: "User verified successfully",
    otpSendMessage: "Otp sent successfully",
    missingFieldsMessage: "Please provide all required fields",
    loginLockedMessage: "Login attempts exceeded. Please try again later",
    badAuthMessage: "Invalid email or password",
    unAuthorizedMessage: "Please login to access this resource",
    logoutMessage: "Logged out successfully",
    userProfileFoundMessage: "User profile found",
    userProfileUpdatedMessage: "User profile updated successfully",
    userNotVerifiedMessage: "User not verified. Please verify your email",
    postCreatedMessage: "Post created successfully",
    postNotFoundMessage: "Post not found",
    postUpdatedMessage: "Post updated successfully",
    postDeletedMessage: "Post deleted successfully",
    postsNotFoundMessage: "No Post found",
    postsFoundMessage: "Posts found",
}